### ISSUE TITLE
Start print in different way?

### ISSUE THREAD

**Issue by Despx72** [stiliajohny/Ansible-Provisioning#122]
**@stiliajohny : PLEASE before blocking again the topic with cryptic errors... explain for dummies where I wrong repo. Thank you very much :-)**

Hi All, this is my custom start GCode:

**G28 ;Home
G4 P1000
G0 Y180 Z150 F1500;Move the Y to 180mm and Z at 150mm
G4 P5000
G92 E0
G1 F200 E25 ;extrude 25mm of feed stock
M203 X500.00 Y500.00 Z10.00 E50.00 ;Setup machine max feedrate
M220 S100 ;Reset Feedrate
M221 S100 ;Reset Flowrate**

So far everything is fine but when the print starts, the nozle is lowered to the height of the layer and then dangerously moved to the XY coordinates of the start of the print because if nozzle (for some rason) is not perfectly leveled with the bed can crash with it .

I analyzed the files generated by PrusaSlicer and I don't know why Z and XY movements are separated creating the dangerous movements:

**G1 Z0.100 F6000.000
G1 X51.860 Y109.292**

I tried to move XYZ together with excellent result and no danger zone:

**G0 F6000 X51.860 Y109.292 Z0.100**

How can I make this change automatic when the GCode is generated?

Best Regards
Despx

**Comment by stiliajohny** [comment]
How this issue is related to ansible ?

**Comment by Despx72** [comment]
Excuse my ignorance but what is the term "ansible"?
Did I miss the section where to put the message?

**Comment by Despx72** [comment]
I must have made a mistake ... I want to post the message in Prusa3D but I don't understand why it ended here ... Sorry!
